### PR TITLE
Bugfix/whitenoise

### LINKED ISSUE #21: Disabling DEBUG in settings.py removes HTML formatting
In settings.py DEBUG is turned on. It is recommended for production environments to turn it off.

However, do this and the HTML UI breaks - this doomed #14 

@Greg-Hawkridge says the answer is to use whitenoise to make the staticfiles available. Tell us more and make a PR :)

### PR DESCRIPTION
**Pull request by tobyaharris**
Addresses #21 
@Greg-Hawkridge please advise on best implementation.

### CODE REVIEW

**Comment by tobyaharris** [comment]
Upon searching through job tracking for `whitenoise`: (creds to VSCode's `CTRL SHIFT F`)

`user_input_dc/code/requirements.txt` :
```
whitenoise==5.1.0
```

`location_sds/code/job_locations/settings.py` :
```
INSTALLED_APPS = [
    ...
    'whitenoise',
    ...
```


`user_input_dc/code/site_config/settings.py`  and `location_sds/code/job_locations/settings.py` and `dashboard_ui/code/management_portal/settings.py` : 
```
MIDDLEWARE = [
    ...
    'whitenoise.middleware.WhiteNoiseMiddleware',
    ...
```

Which raises 2 questions for me:
1. Why is whitenoise included in the pip requirements for only 1 of the 3 docker containers / service modules it is used in? Doesn't it need to be installed separately into each?
2. Why is whitenoise only included in the `INSTALLED_APPS` list in a different 1 of the 3 docker containers / service modules? Why does it not need to be included in all 3?

**Comment by Greg-Hawkridge** [comment]
It should be in the `INSTALLED_APPS` for all three as that is best practice, but only needs to be in middleware for it to work. I don't think it explicitly needs to be in requirements.txt for these three service modules as it is already included in the requirements.txt for the pre-baked docker image they use.

**Comment by tobyaharris** [comment]
`user_input_dc` is the only one above not using the `digitalshoestring/shoestring-django(-rest):v0.0.1` image, hence the inclusion in requirements.txt

**Comment by tobyaharris** [comment]
Question to self, why is this still draft?
- Needs testing
- ~Needs comment removal on whitenoise version. Stick with the 5.1 we know.~
- ~Need to implement the purpose of this - disabling DEBUG~

**Comment by tobyaharris** [comment]
This is open to testing and reviewing while I'm away

**Review by Greg-Hawkridge — APPROVED** [review]

**Comment by tobyaharris** [comment]
Tested just now, looks as expected. Does not cause any change from the basic user's perspective.

**Pull request merged**
