### PR TITLE
Headers in downloaded Excel stock reports

### LINKED ISSUE #31: Downloadable Stock Report has no headers
There's a Download Stock Report button in the Stock Management tab
image

The file opens in Excel but the cols have no headers. There are 5 cols that contain only an integer and there is no indication of what they mean. 

Could a row be inserted at the top with a word or two describing the data below? Looks like A is an identifier and H is cost, but C, F and G are guesswork.

### PR DESCRIPTION
**Pull request by anandarupmukherjee**
Addresses #31

### CODE REVIEW

**Comment by tobyaharris** [comment]
Tested just now. Built from scratch and navigated to the Stock Management page on a windows machine. Downloaded a report. Opens fine in Excel. Looks like this: 
image
Ah. Where's the headers?

**Comment by tobyaharris** [comment]
Opening the download on a pi looks like this: 
image
I don't see any sign of headers in the file.

**Review by tobyaharris — CHANGES_REQUESTED** [review]
Unfortunately this hasn't solved the issue! See testing notes.

**Comment by tobyaharris** [comment]
Rebuilding in progress! Thanks for the speedy fix.

**Comment by anandarupmukherjee** [comment]
Sorted. Missed a line in the code. Should work now.

**Comment by tobyaharris** [comment]
Better -  headers ahoy. But the location is an int, is is possible to convert back to meaningful string?
image
image

**Comment by tobyaharris** [comment]
Locations can't be translated back to strings easily. As this isn't an important feature, I'm tempted to say some headers are better than none and keep that as a known issue.

**Review by tobyaharris — APPROVED** [review]

**Pull request merged**
